### ISSUE TITLE
Driver initialization in C# OpenSDK sends a report to agent (called "InvokeMethod")

### ISSUE THREAD

**Issue by amitlubintp** [testproject-io/csharp-opensdk#142] opened 2021-03-18 15:44 UTC
In C# OpenSDK (Using Xunit) , a report is sent to agent. The report is called "InvokeMethod".

**Comment by basdijkstra** [comment] 2021-03-18 15:49
Do you have an example that I can use to reproduce this issue, @amitlubintp? Without it there is no way to find out why this is happening.

**Comment by Rantzur1992** [comment] 2021-03-21 07:25
@basdijkstra  I saw in one of your other issues that you had the method in the report.
Why not juist implement the same thing we did in Python back then?
Add an option to supply a list of names to the drivers to ignore in the reports.

**Comment by basdijkstra** [comment] 2021-03-22 07:30
If that's an acceptable solution to this issue we can change this to a feature request / enhancement. But I'd like to see an example that reproduces this issue first from @amitlubintp because that's the only way to determine what the problem is here.

**Comment by basdijkstra** [comment] 2021-03-22 07:42
Let me investigate the example first to see what the real problem is and if there isn't a better solution. If there isn't we can always discuss solutions like this.

**Comment by kishangupta-15** [comment] 2021-03-22 08:32
@basdijkstra @Rantzur1992 this is same as #141. You can use the same example.

**Comment by Rantzur1992** [comment] 2021-03-22 09:38
Thanks @kishangupta-15

**Comment by basdijkstra** [comment] 2021-03-25 05:47
If this is the same as #141, it has been resolved by #153. @amitlubintp can you retest with the latest prerelease this once that PR has been merged?

**Comment by basdijkstra** [comment] 2021-03-25 15:20
PR #153 has been merged and released in https://www.nuget.org/packages/TestProject.OpenSDK/0.66.0.372-rc. Please retest and close this issue when you're happy with the result.

**Comment by Rantzur1992** [comment] 2021-04-08 09:12
@kishangupta-15 Can you double-check if it's okay and update this ticket, please.

**Comment by kishangupta-15** [comment] 2021-04-09 06:23
@Rantzur1992, @basdijkstra I have verified this and it is working fine now. Since I have not logged this issue here, I am unable to close it. You guys please go ahead and close it.

**Comment by basdijkstra** [comment] 2021-04-09 06:34
Thank you for confirming. Closing this issue.

**Closed by basdijkstra** 2021-04-09 06:34 UTC
Labels: resolved
