### ISSUE TITLE
[NUnit] elementDictionary (Parameter 'The specified dictionary does not contain an element reference')'

### ISSUE THREAD

**Issue by dorbenzvi** [testproject-io/csharp-opensdk#117] opened 2021-02-28 13:30 UTC
While trying to locate an element I got this error:
elementDictionary (Parameter 'The specified dictionary does not contain an element reference')'

Got this when trying to find the element.

![image](https://user-images.githubusercontent.com/55704483/109420213-e2828200-79d9-11eb-98f6-6317a5befae1.png)

My Code:

````
using NUnit.Framework;

namespace NUnitTestProject1
{
    using System; 
    using OpenQA.Selenium;
    using OpenQA.Selenium.Appium;
    using OpenQA.Selenium.Appium.Enums;
    using OpenQA.Selenium.Remote;
    using TestProject.OpenSDK.Exceptions;
    using TestProject.OpenSDK.Drivers.Android;
```

    [TestFixture]
    public class AndroidDriverTest
    {
        private readonly string dutUdid ="Device_ID";

        private readonly string autPackageName = "com.google.android.apps.maps";

        private readonly string autActivityName ="com.google.android.maps.MapsActivity";

        /// <summary>
        /// The TestProject AndroidDriver instance to be used in this test class.
        /// </summary>
        private AndroidDriver<AppiumWebElement> driver;

        /// <summary>
        /// Starts an Android driver with required AppiumOptions before each test.
        /// </summary>
        [SetUp]
        public void StartDriver()
        {
            if (this.autActivityName == null || this.autPackageName == null || this.dutUdid == null)
            {
                throw new SdkException("Not all required environment variables were set before the start of the test.");
            }

            AppiumOptions appiumOptions = new AppiumOptions();

            appiumOptions.AddAdditionalCapability(MobileCapabilityType.PlatformName, MobilePlatform.Android);
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.Udid, this.dutUdid);
          
            appiumOptions.AddAdditionalCapability(CapabilityType.BrowserName, string.Empty);
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.DeviceName, "google-pixel_3_xl-96HY1BJGH");
            appiumOptions.AddAdditionalCapability(AndroidMobileCapabilityType.AppPackage, this.autPackageName);
            appiumOptions.AddAdditionalCapability(AndroidMobileCapabilityType.AppActivity, this.autActivityName);

            this.driver = new AndroidDriver<AppiumWebElement>(token: "My_token_here", appiumOptions: appiumOptions);

            this.driver.StartActivity(appPackage: this.autPackageName, appActivity: this.autActivityName);
        }

        /// <summary>
        /// An example test logging in to the TestProject native demo application on Android.
        /// </summary>
        /// 
        [Test]
        public void Test()
        {
            this.driver.FindElement(By.XPath("//android.widget.EditText[@text = 'Search here']")).SendKeys("John Smith");
            Assert.IsTrue(this.driver.FindElement(By.Id("greetings")).Displayed);
        }

        /// <summary>
        /// Closes the browser and ends the development session after each test.
        /// </summary>
        [TearDown]
        public void CloseBrowser()
        {
            this.driver.Quit();
        }
    }
}`

**Comment by dorbenzvi** [comment] 2021-02-28 15:56
@basdijkstra 
I found it happens when it cannot find the element by this XPath, this should be the error?

**Comment by basdijkstra** [comment] 2021-03-01 09:33
There's probably a better way to handle this situation.. Thanks for reporting this.

**Comment by basdijkstra** [comment] 2021-03-01 10:00
I've just submitted #121, which improves the exception handling when an element is not found by throwing a custom `ElementNotFoundException` in those cases where `FindElement` fails.

@dorbenzvi please retest this with the latest OpenSDK prerelease version once this PR has been merged.

**Comment by Rantzur1992** [comment] 2021-03-07 09:24
@basdijkstra  Using the latest pre-release on IOS still throws that message when an element is not found.

**Comment by basdijkstra** [comment] 2021-03-07 12:42
> @basdijkstra Using the latest pre-release on IOS still throws that message when an element is not found.

Are you using the FindElement() method from a driver or from an IWebElement? If the latter, please see #92. I do not know yet how to solve this.

**Comment by dorbenzvi** [comment] 2021-03-07 12:44
@basdijkstra Tested it on 0.65.1.341 and I still got the same exception.

` Message: 
    System.ArgumentException : elementDictionary (Parameter 'The specified dictionary does not contain an element reference')
  Stack Trace: 
    RemoteWebElementFactory.GetElementId(Dictionary`2 elementDictionary)
    CachedElementFactory`1.CreateElement(Dictionary`2 elementDictionary)
    RemoteWebDriver.GetElementFromResponse(Response response)
    RemoteWebDriver.FindElement(String mechanism, String value)
    RemoteWebDriver.FindElementByXPath(String xpath)
    <>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
    By.FindElement(ISearchContext context)
    RemoteWebDriver.FindElement(By by)
    AppiumDriver`1.FindElement(By by)
    Tests.Test() line 54`

**Comment by basdijkstra** [comment] 2021-03-07 12:57
I see in the stack trace that it calls By.FindElement(), and that’s where the problem is. Same issue as in #92.

My suggestion would be to close this one and continue the discussion there.

**Comment by basdijkstra** [comment] 2021-03-20 07:23
0.66.0 is released, please retest and close this issue when you feel it's resolved: https://www.nuget.org/packages/TestProject.OpenSDK/0.66.0

**Comment by Rantzur1992** [comment] 2021-03-21 07:46
@basdijkstra NUnit test on mobile, it still happens when the element is not found.

![image](https://user-images.githubusercontent.com/6703682/111897704-25a8a180-8a2a-11eb-9e03-f6efbd2433d2.png)

**Comment by Rantzur1992** [comment] 2021-03-21 07:55
Code:

```
using NUnit.Framework;
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Enums;
using OpenQA.Selenium.Appium.iOS;
using OpenQA.Selenium.Interactions;
using System.Threading;

namespace ios_tests
{
    public class Tests
    {
        private readonly string deviceId = "";

        private readonly string deviceName = "iPhone";

        private readonly string bundleId = "com.google.ios.youtube";

        TestProject.OpenSDK.Drivers.IOS.IOSDriver<IOSElement> driver;

        public TestProject.OpenSDK.Drivers.IOS.IOSDriver<IOSElement> Driver
        {
            get
            {
                Thread.Sleep(3000);
                return this.driver;
            }
            set
            {
                this.driver = value;
            }
        }

        [SetUp]
        public void Setup()
        {
            AppiumOptions options = new AppiumOptions();
            options.AddAdditionalCapability(MobileCapabilityType.PlatformName, MobilePlatform.IOS);
            options.AddAdditionalCapability(MobileCapabilityType.Udid, this.deviceId);

            options.AddAdditionalCapability(MobileCapabilityType.DeviceName, this.deviceName);
            options.AddAdditionalCapability(IOSMobileCapabilityType.BundleId, this.bundleId);

            Driver = new TestProject.OpenSDK.Drivers.IOS.IOSDriver<IOSElement>(appiumOptions: options);
        }

        [Test]
        public void SearchIntroAndClick()
        {
            searchRun();
            Driver.FindElementByAccessibilityId("id.ui.pivotbar.FEwhat_to_watch.button").Click();
            Driver.FindElementByAccessibilityId("id.ui.pivotbar.FEexplore.button").Click();
            Driver.FindElementByAccessibilityId("id.ui.pivotbar.FEsubscriptions.button").Click();
            Driver.FindElementByAccessibilityId("id.ui.pivotbar.FElibrary.button").Click();


            searchRun();
            // Driver.FindElement(by: OpenQA.Selenium.By.XPath("//XCUIElementTypeOther/XCUIElementTypeButton[1]/XCUIElementTypeButton")).Click();
            var result = false;
            Assert.IsFalse(result);
        }

        [TearDown]
        public void TearDown()
        {
            Driver.Quit();
        }

        private void searchRun()
        {
            Driver.FindElementByAccessibilityId("id.ui.navigation.search.button").SendKeys("Techno");
            Driver.FindElementByAccessibilityId("techno, Search suggestion").Click();
            TouchActions actions = new TouchActions(driver);
            // var element = driver.FindElementByAccessibilityId("1 hour, 25 seconds, Techno Mix – March 2019, Human Music · 12M views · 2 years ago");
            actions.Scroll(element,
                10,
                100);
            element.Click();
        }
    }
}
```

The commented line is the issue, the element is found in the recorder but for some reason in the SDK it always throws that exception.

**Comment by basdijkstra** [comment] 2021-03-22 07:33
Again, this is the same issue as #92. Can we close this one and continue the discussion there?

**Comment by Rantzur1992** [comment] 2021-03-22 07:45
Yes, I don't have the ability to close this.

**Comment by basdijkstra** [comment] 2021-03-22 07:47
I do, though :) Thanks.

**Closed by basdijkstra** 2021-03-22 07:47 UTC
Labels: resolved
