### ISSUE TITLE
OpenSDK Wrong job name.

### ISSUE THREAD

**Issue by dorbenzvi** [testproject-io/csharp-opensdk#140] opened 2021-03-18 10:04 UTC
Hi, when using a Base class the job name is the wrong Job name.

My Code without Job name:

Base:
```
using System;
using TestProject.OpenSDK.Drivers.Web;

namespace XUnitTestProject2
{
    public class BaseTest 
    {
        public ChromeDriver Driver;

        public BaseTest()
        {
            Driver = new ChromeDriver(projectName: "PANDA2",token: "Token_here");
        }

   
    }
}
```

Test:

```
namespace XUnitTestProject2
{
    using OpenQA.Selenium;
    using TestProject.OpenSDK.Drivers.Generic;
    using TestProject.OpenSDK.Drivers.Web;
    using Xunit;
    using TestProject.OpenSDK.Internal.CallStackAnalysis;
    using Xunit.Abstractions;
    public class OpenSdk : BaseTest
    {
        private readonly ITestOutputHelper _testOutputHelper;
        private const string XUnitNamespace = "XUnit";
        private const string TestNameProperty = "DisplayName";
        private static readonly string[] AttributeNames = { "Fact", "Theory" };
        [Fact]
        public void Test1()
        {
            //var Driver = new ChromeDriver();

            Driver.Navigate().GoToUrl("https://example.testproject.io");
            Driver.FindElement(By.CssSelector("#name")).SendKeys("John Smith");
            Driver.FindElement(By.CssSelector("#password")).SendKeys("12345");
            Driver.FindElement(By.CssSelector("#login")).Click();
            Assert.True(Driver.FindElement(By.CssSelector("#greetings")).Displayed);

            Driver.Quit();
        }


        public OpenSdk(ITestOutputHelper testOutputHelper)
        {
            _testOutputHelper = testOutputHelper;
        }


    }
}
```

Report:

![image](https://user-images.githubusercontent.com/55704483/111608630-1b946200-87e2-11eb-929b-013b30e5d47a.png)

**Comment by basdijkstra** [comment] 2021-03-18 11:27
Thank you for reporting that. I'll see if that can be improved.

**Comment by basdijkstra** [comment] 2021-03-19 09:36
I'm able to reproduce this issue on my machine, I'll see if I can find a solution for it. The challenge will be to find a reference to the actual test method in the stack trace at the moment you're initializing the driver in a different method in the base class, so far I haven't found one yet. If I can't find one, I don't think it's possible to infer the proper job name automatically... But we'll see.

**Comment by basdijkstra** [comment] 2021-03-19 12:23
OK, after some more debugging I can't find a way to fix this. At the moment when the driver is created, we're not inside a test method (`Fact` or `Theory`), nor in a class that contains these methods. There's a reference to the `OpenSdk` class in the stack trace, but since xUnit does not require class-level annotations, there is no way to be sure that this is the class that contains the test methods (it could be yet another class that the actual test class extends, for example).

That means that unfortunately I see no way to reliably support auto-inferring of job names in this specific case..

**Comment by basdijkstra** [comment] 2021-03-23 07:25
Hmm.. Now that I'm working on #150, there might be a solution to this after all. Now trying to make the logic as simple as possible while still covering all the cases.

**Comment by basdijkstra** [comment] 2021-03-23 17:53
It looks like I've found a way to make this work. When using a test similar to this one, the output now looks like this:

![image](https://user-images.githubusercontent.com/10740451/112194164-e4221d00-8c08-11eb-9f2b-aa384b527142.png)

The driver is created in the constructor of a base class.

Please retest this with the latest prerelease once #153 has been merged, @dorbenzvi.

**Comment by basdijkstra** [comment] 2021-03-25 15:21
PR #153 has been merged and released in https://www.nuget.org/packages/TestProject.OpenSDK/0.66.0.372-rc. Please retest and close this issue when you're happy with the result.

**Comment by Rantzur1992** [comment] 2021-04-08 09:11
Verified, closing.

**Closed by Rantzur1992** 2021-04-08 09:11 UTC
Labels: resolved
