### ISSUE TITLE
FindElements function of driver is marked as failed in the report if it doesn't return any elements

### ISSUE THREAD

**Issue by kishangupta-15** [testproject-io/csharp-opensdk#216] opened 2021-06-25 14:05 UTC
The FindElements method of selenium driver returns an array of WebElements as per selector. When it doesn't find any elements, it returns a empty array.

However, testproject driver is reporting the empty array case as a failure in the reports. In many cases, FindElements method is used to verify the existence of the element in the DOM. So, the empty array returned by FindElements method should not be marked as failed. this goes against the intended use of this method.

This method should only be failed in the below cases:
1) In case of an error while executing the method
2) In case returned array of WebElements is empty and user tries to perform some action on the empty array
3) In case, user manually marks this as failed

![image](https://user-images.githubusercontent.com/54025467/123430240-93460a00-d5e5-11eb-85ef-003f8a9e898c.png)

**Comment by mstrelex** [comment] 2021-06-28 12:32
@kishangupta-15 

Thanks for reporting this.
It will be handled at the earliest.

**Comment by Artem-Kuz** [comment] 2021-06-29 07:29
@mstrelex @kishangupta-15 I have investigated and found that the root cause of this issue is in the agent and not the OpenSDK.
a fix will be released in one of the next agent releases.

**Closed by Artem-Kuz** 2021-06-29 07:29 UTC
Labels: bug
