### ISSUE TITLE
Cleanup steps falsely try to start a new driver session

### ISSUE THREAD

**Issue by Rantzur1992** [testproject-io/csharp-opensdk#47] opened 2021-01-10 12:46 UTC
Specflow test.
Feature:
```
Feature: To create some step
	In order to create a step, I need a feature


Scenario: Ran Tries to click a button
    Given Ran wants to click a button
	When He tries to click the button
	Then the Button is clicked
```

Code:
```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium;
using TechTalk.SpecFlow;
using TestProject.OpenSDK.Drivers.Web;

namespace TestingMSTest.StepDefenitions
{
    [Binding]
    public class ToCreateSomeStepSteps
    {

        private ChromeDriver driver;
        private IWebElement button;

        [Before]
        public void StartBrowser()
        {
            this.driver = new ChromeDriver();
            driver.Navigate().GoToUrl("https://example.testproject.io/web/");
        }

        [Given(@"Ran wants to click a button")]
        public void GiveRanWantsToClickAButton()
        {
            this.button = driver.FindElement(By.XPath("//button[@id='login'"));
        }
        
        [When(@"He tries to click the button")]
        public void WhenHeTriesToClickTheButton()
        {
            this.button.Click();
        }
        
        [Then(@"the Button is clicked")]
        public void ThenTheButtonIsClicked()
        {
            Assert.IsTrue(this.driver.FindElement(By.XPath("//div[@class='invalid-feedback']")).Text.Equals("Password is invalid"));
        }

        [After]
        public void CloseBrowser()
        {
            this.driver.Quit();
        }
    }
}
```
Error:
```
Test Name:	RanTriesToClickAButton
Test FullName:	TestingMSTest.TestingMSTest.Features.ToCreateSomeStepFeature.RanTriesToClickAButton
Test Source:	C:\Users\rantz\source\repos\TestingMSTest\TestingMSTest\Features\SpecFlowFeature1.feature : line 5
Test Outcome:	Failed
Test Duration:	0:00:00

Test Name:	RanTriesToClickAButton
Test Outcome:	Failed
Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebElementFactory.GetElementId(Dictionary`2 elementDictionary)
   at OpenQA.Selenium.Remote.RemoteWebElementFactory.CreateElement(Dictionary`2 elementDictionary)
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetElementFromResponse(Response response)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at TestingMSTest.StepDefenitions.ToCreateSomeStepSteps.GiveRanWantsToClickAButton() in C:\Users\rantz\source\repos\TestingMSTest\TestingMSTest\StepDefenitions\ToCreateSomeStepSteps.cs:line 25
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TestProject.SpecFlowPlugin.TestProjectBindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
   at TestingMSTest.Features.ToCreateSomeStepFeature.ScenarioCleanup()
   at TestingMSTest.Features.ToCreateSomeStepFeature.RanTriesToClickAButton() in C:\Users\rantz\source\repos\TestingMSTest\TestingMSTest\Features\SpecFlowFeature1.feature:line 8

TestCleanup Stack Trace
   at TestProject.OpenSDK.Internal.Rest.AgentClient.HandleSessionStartFailure(IRestResponse startSessionResponse)
   at TestProject.OpenSDK.Internal.Rest.AgentClient.StartSession(ReportSettings reportSettings, DriverOptions capabilities)
   at TestProject.OpenSDK.Internal.Rest.AgentClient..ctor(Uri remoteAddress, String token, DriverOptions capabilities, ReportSettings reportSettings, Boolean disableReports, Version compatibleVersion)
   at TestProject.OpenSDK.Internal.Rest.AgentClient.GetInstance(Uri remoteAddress, String token, DriverOptions capabilities, ReportSettings reportSettings, Boolean disableReports, Version compatibleVersion)
   at TestProject.OpenSDK.Internal.Rest.AgentClient.GetInstance()
   at TestProject.OpenSDK.Internal.Helpers.CommandExecutors.ReportingCommandExecutor.ReportCommand(Command command, Response response)
   at TestProject.OpenSDK.Internal.Helpers.CommandExecutors.CustomHttpCommandExecutor.Execute(Command commandToExecute, Boolean skipReporting)
   at TestProject.OpenSDK.Internal.Helpers.CommandExecutors.CustomHttpCommandExecutor.Execute(Command commandToExecute)
   at TestProject.OpenSDK.Drivers.BaseDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Dispose(Boolean disposing)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Dispose()
   at OpenQA.Selenium.Remote.RemoteWebDriver.Quit()
   at TestProject.OpenSDK.Drivers.BaseDriver.Stop()
   at TestProject.OpenSDK.Drivers.BaseDriver.Quit()
   at TestingMSTest.StepDefenitions.ToCreateSomeStepSteps.CloseBrowser() in C:\Users\rantz\source\repos\TestingMSTest\TestingMSTest\StepDefenitions\ToCreateSomeStepSteps.cs:line 43
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TestProject.SpecFlowPlugin.TestProjectBindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.InvokeHook(IBindingInvoker invoker, IHookBinding hookBinding, HookType hookType)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType hookType)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioEnd()
   at TechTalk.SpecFlow.TestRunner.OnScenarioEnd()
   at TestingMSTest.Features.ToCreateSomeStepFeature.TestTearDown()
Result Message:	
Test method TestingMSTest.Features.ToCreateSomeStepFeature.RanTriesToClickAButton threw exception: 
System.ArgumentException: elementDictionary (Parameter 'The specified dictionary does not contain an element reference')
TestCleanup method TestingMSTest.Features.ToCreateSomeStepFeature.TestTearDown threw exception. TestProject.OpenSDK.Internal.Exceptions.InvalidTokenException: TestProject.OpenSDK.Internal.Exceptions.InvalidTokenException: Provided token for 'Development' session is invalid!.
Result StandardOutput:	
-> Loading plugin C:\Users\rantz\source\repos\TestingMSTest\TestingMSTest\bin\Debug\netcoreapp3.1\TechTalk.SpecFlow.MSTest.SpecFlowPlugin.dll
-> Loading plugin C:\Users\rantz\source\repos\TestingMSTest\TestingMSTest\bin\Debug\netcoreapp3.1\TestProject.SpecFlowPlugin.dll
-> Using default config
Given Ran wants to click a button
-> error: elementDictionary (Parameter 'The specified dictionary does not contain an element reference')
When He tries to click the button
-> skipped because of previous errors
Then the Button is clicked
-> skipped because of previous errors
```

Agent logs show the dev token is not passed from the SDK:
`GET https://api.testproject.io/api/v1/agent/tokens?type=Development&token= - 400 (h8HRAJen): Bad data was provided: A value is required but was not present in the request.`

**Comment by basdijkstra** [comment] 2021-01-19 08:43
So I've been able to reproduce this on my own machine, @Rantzur1992, but it only happened because I accidentally tried to call `driver.Quit()` twice. I had two different step definition files, both with the following method:

```csharp
[After]
public void CloseBrowser()
{
    this.driver.Quit();
}
```
Since SpecFlow looks in all classes annotated with `[Binding]` for hooks, it will execute both `[After]` methods. When I commented out the `this.driver.Quit();` on one of them, the error message disappeared.

Did you accidentally do the same (i.e., have two different `[Binding]` classes containing step definitions in the same project)?

In the meantime, I'll add some more graceful handling of this situation.

**Comment by basdijkstra** [comment] 2021-01-20 08:32
I have just submitted #67, which should improve the error handling, @Rantzur1992. Could you have another look when that one is merged? The easiest way to test it is to simply call `driver.Quit()` twice.

**Comment by basdijkstra** [comment] 2021-01-28 09:57
Hey @Rantzur1992, what can we do to get this issue off the list? Can you test again with the latest (prerelease) version? Should I do anything? I'd like to clean up the issue list.

**Comment by basdijkstra** [comment] 2021-02-18 15:36
Closing this issue since there's been no activity for three weeks. Feel free to reopen it if you think it has not been properly addressed, @Rantzur1992.

**Closed by basdijkstra** 2021-02-18 15:36 UTC
Labels: resolved
