### ISSUE TITLE
ResetApp throws System.NullReferenceException

### ISSUE THREAD

**Issue by AlonGabbay** [testproject-io/csharp-opensdk#125] opened 2021-03-02 17:57 UTC
When i try to run a test and use the resetApp, System.NullReferenceException is thrown after the application is correctly reset

```c#
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject1
{
    using System;
    using System.Threading;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using OpenQA.Selenium;
    using OpenQA.Selenium.Appium;
    using OpenQA.Selenium.Appium.Enums;
    using OpenQA.Selenium.Remote;
    using TestProject.OpenSDK.Drivers.Android;
    using TestProject.OpenSDK.Exceptions;

    /// <summary>
    /// This class contains examples of using the TestProject C# SDK with a native Android app.
    /// </summary>
    [TestClass]
    public class AndroidDriverTest
    {
        private readonly string dutUdid = Environment.GetEnvironmentVariable("TP_ANDROID_DUT_UDID");

        private readonly string autPackageName = Environment.GetEnvironmentVariable("TP_ANDROID_AUT_PACKAGE");

        private readonly string autActivityName = Environment.GetEnvironmentVariable("TP_ANDROID_AUT_ACTIVITY");

        /// <summary>
        /// The TestProject AndroidDriver instance to be used in this test class.
        /// </summary>
        private AndroidDriver<AppiumWebElement> driver;

        /// <summary>
        /// Starts an Android driver with required AppiumOptions before each test.
        /// </summary>
        [TestInitialize]
        public void StartDriver()
        {
            if (this.autActivityName == null || this.autPackageName == null || this.dutUdid == null)
            {
                throw new SdkException("Not all required environment variables were set before the start of the test.");
            }

            AppiumOptions appiumOptions = new AppiumOptions();

            appiumOptions.AddAdditionalCapability(MobileCapabilityType.PlatformName, MobilePlatform.Android);
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.Udid, this.dutUdid);

            appiumOptions.AddAdditionalCapability(CapabilityType.BrowserName, string.Empty);
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.DeviceName, "xiaomi-redmi_note_6_pro-4beecc2f");
            appiumOptions.AddAdditionalCapability(AndroidMobileCapabilityType.AppPackage, this.autPackageName);
            appiumOptions.AddAdditionalCapability(AndroidMobileCapabilityType.AppActivity, this.autActivityName);

            this.driver = new AndroidDriver<AppiumWebElement>(appiumOptions: appiumOptions);

            this.driver.StartActivity(appPackage: this.autPackageName, appActivity: this.autActivityName);
        }

        /// <summary>
        /// An example test logging in to the TestProject native demo application on Android.
        /// </summary>
        [TestMethod]
        public void ExampleTestUsingAndroidDriver()
        {
            this.driver.ResetApp();
            // 2. Click 'כן, זה בסדר'
            // Add step sleep time (Before)
            //this.driver.FindElement(By.Id("com.android.packageinstaller:id/permission_allow_button")).Click();
            //this.driver.FindElement(By.Id("name")).SendKeys("John Smith");
            //this.driver.FindElement(By.Id("password")).SendKeys("12345");
            //this.driver.FindElement(By.Id("login")).Click();
            Assert.IsTrue(true);
            // Assert.IsTrue(this.driver.FindElement(By.Id("greetings")).Displayed);
        }

        /// <summary>
        /// Closes the browser and ends the development session after each test.
        /// </summary>
        [TestCleanup]
        public void CloseBrowser()
        {
            this.driver.Quit();
        }
    }
}
```

**Comment by basdijkstra** [comment] 2021-03-03 08:56
Thank you for reporting this, @AlonGabbay. I'll have a look as soon as possible.

**Comment by basdijkstra** [comment] 2021-03-11 14:26
It seems like for some reason not all Appium-specific command are properly added to the command info repository. As a result, getting the `CommandInfo` for the `ResetApp` command fails because of a `NullReferenceException`. Investigating.

**Comment by basdijkstra** [comment] 2021-03-12 10:52
I've just submitted #134, which addresses this issue. The problem was that while I did add Appium-specific commands to the driver objects, somehow I overlooked doing the same in our custom HTTP command executor. That's been fixed, and as a result Appium-specific commands such as `ResetApp()` can now be executed successfully.

@AlonGabbay, when this PR is merged, please retest it with the latest prerelease, that will include the fix. If you think the issue is addressed properly, please close this issue.

**Comment by basdijkstra** [comment] 2021-03-17 07:37
#134 is merged, so you can retest this with the latest prerelease, @AlonGabbay.

**Comment by AlonGabbay** [comment] 2021-03-17 08:07
Hi Bass,
I resigned from testproject.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by basdijkstra** [comment] 2021-03-17 08:12
Thank you for letting me know, and all the best! I've tested this myself as well and it seems to work, so I'm closing this issue.

**Closed by basdijkstra** 2021-03-17 08:12 UTC
Labels: resolved
