### ISSUE TITLE
Impossible to create session with certain capabilities

### ISSUE THREAD

**Issue by AnnaSwietek** [testproject-io/csharp-opensdk#239] opened 2021-07-29 08:52 UTC
OpenSDK 1.1.1
TP Agent 3.1.0.618

**Error:** Agent responsed with status code 500: [Unable to create session from {
  "desiredCapabilities"

**Capabilities sent by us:**
Creating session with W3C capabilities: {
  "alwaysMatch": {
    "appium:deviceName": null,
    "appium:dontStopAppOnReset": true,
    "appium:noReset": false,
    "appium:fullReset": false,
    "appium:unicodeKeyboard": true,
    "appium:resetKeyboard": true,
    "appium:automationName": "UIAutomator2",
    "platformName": "Android",
    "browserName": "Chrome",
    "goog:chromeOptions": {
      "w3c": false
    }
  },
  "firstMatch": [
    {}
  ]
}

It is impossible to create session with above capabilities. With Vanilla Appium session gets created without any problems.

**See logs:**
Tricentis.Automation.Engines.Technicals.SutException: Agent responsed with status code 500: [Unable to create session from {
  "desiredCapabilities": {
    "settings[waitForIdleTimeout]": 0,
    "noReset": false,
    "dontStopAppOnReset": true,
    "settings[shouldUseCompactResponses]": false,
    "fullReset": false,
    "settings[elementResponseAttributes]": "resourceId,displayed,enabled,className,text,attribute\u002fresourceId,attribute\u002fresource-id,attribute\u002fdisplayed,attribute\u002fenabled,attribute\u002fclassName,attribute\u002fchecked",
    "settings[waitForSelectorTimeout]": 0,
    "goog:chromeOptions": {
      "args": [
        "--disable-breakpad"
      ],
      "extensions": [
      ],
      "w3c": false,
      "binary": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
    },
    "automationName": "UIAutomator2",
    "browserName": "Chrome",
    "unicodeKeyboard": true,
    "platformName": "Android",
    "resetKeyboard": true
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "Chrome",
        "goog:chromeOptions": {
          "args": [
            "--disable-breakpad"
          ],
          "extensions": [
          ],
          "w3c": false,
          "binary": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
        },
        "platformName": "android"
      }
    ]
  }
}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-520GJPR', ip: '192.168.150.25', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '13.0.1'
Driver info: driver.version: unknown
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-520GJPR', ip: '192.168.150.25', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '13.0.1'
Driver info: driver.version: unknown]

**Comment by s-glatshtein** [comment] 2021-08-03 15:53
Hi Anna. Can you please share the code that creates your capabilities?

**Comment by s-glatshtein** [comment] 2021-08-18 07:23
Hi Anna. I took another look at the capabilities. I understand the issue is you do not specify device UDID. As a temporary workaround is it possible that you supply the UDID until we support this kind of scenario?

**Comment by AnnaSwietek** [comment] 2021-08-23 12:32
Yes, it is possible.

**Comment by mstrelex** [comment] 2021-08-23 18:01
We will add additional logic for this in Agent 3.3.0.
When the UDID is not provided, the agent will search for the first available device and start the automation session there.

**Comment by s-glatshtein** [comment] 2021-09-14 15:34
Closing issue as agent 3.3.0 was released with a solution for this problem

**Closed by s-glatshtein** 2021-09-14 15:34 UTC
