### ISSUE TITLE
App does not start without explicit call to StartActivity()

### ISSUE THREAD

**Issue by basdijkstra** [testproject-io/csharp-opensdk#147] opened 2021-03-22 07:37 UTC
When we create a driver for a test like this:

```csharp
[TestInitialize]
public void StartDriver()
{
        AppiumOptions capabilities = new AppiumOptions();

        capabilities.AddAdditionalCapability(AndroidMobileCapabilityType.NoSign, true);
        capabilities.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
        capabilities.AddAdditionalCapability(MobileCapabilityType.Udid, "emulator-5554");
        capabilities.AddAdditionalCapability(MobileCapabilityType.AutomationName, AutomationName.AndroidUIAutomator2);
        capabilities.AddAdditionalCapability(AndroidMobileCapabilityType.UnicodeKeyboard, true);
        capabilities.AddAdditionalCapability(AndroidMobileCapabilityType.ResetKeyboard, true);
        capabilities.AddAdditionalCapability("dontStopAppOnReset", true);
        capabilities.AddAdditionalCapability("noReset", true);
        capabilities.AddAdditionalCapability("fullReset", false);
        capabilities.AddAdditionalCapability("appActivity", "MainActivity");
        capabilities.AddAdditionalCapability("appPackage", "io.testproject.demo");

        this.driver = new AndroidDriver<AppiumWebElement>(remoteAddress: new Uri("http://127.0.0.1:8585/"), appiumOptions: capabilities);
        this.driver.ResetApp();

        // this.driver.StartActivity(appPackage: "io.testproject.demo", appActivity: "MainActivity");
}
````
a session is started but the app we want to test does not automatically load. To do that we need an explicit call to `this.driver.StartActivity()`. In Appium, this is not necessary: when I replace the TestProject driver for a vanilla Appium `AndroidDriver`, the above code works like a charm.

**Comment by basdijkstra** [comment] 2021-04-08 09:27
I can't reproduce this. I've changed the activity name to just `MainActivity` (for the TestProject demo app), which results in this session request payload:

```json
{
   "capabilities":{
      "platformName":"Android",
      "udid":"emulator-5554",
      "browserName":"",
      "deviceName":"Pixel_3a_API_29_x86 [emulator-5554]",
      "appPackage":"io.testproject.demo",
      "appActivity":"MainActivity"
   },
   "sdkVersion":"0.64.4",
   "language":"CSharp",
   "projectName":"Drivers",
   "jobName":"AndroidDriverTest",
   "reportType":"CLOUD_AND_LOCAL"
}
```
and that starts a new session without problems.

**Comment by basdijkstra** [comment] 2021-04-09 11:39
At first glance it *looks* like the `ResetApp()` call automatically restarts the activity in Appium but fails to do that in TestProject. Which is strange, because our driver is a simple extension of the Appium driver... Will need to dive into this a little deeper.

**Comment by basdijkstra** [comment] 2021-04-09 12:45
@mstrelex @s-glatshtein do you have any idea what could cause this behaviour?

When I use vanilla Appium, my emulator screen shows the app right after a call to `ResetApp()`, whereas the TestProject driver, which is a direct extension of the Appium driver, shows a blank screen after `ResetAp()`. I'm running the exact same test with the exact same capabilities.

**Comment by mstrelex** [comment] 2021-04-09 13:23
I believe that this happens since besides the capabilities provided in the snippet above there are also "hard-coded" capabilities that TestProject AGent sends, among which there is the "norest=true" that might cause this behavior.

@Rantzur1992 Could you please investigate and propose an Agent fix if required?

**Comment by basdijkstra** [comment] 2021-04-09 13:30
Thanks @mstrelex, I'm reassigning this to @Rantzur1992 for now.

**Comment by Rantzur1992** [comment] 2021-04-12 06:16
I will check it out.

**Comment by basdijkstra** [comment] 2021-04-15 04:00
Any news on this one, @Rantzur1992 ?

**Comment by Rantzur1992** [comment] 2021-04-18 07:34
@basdijkstra I am checking it now on the Agent side.
Since this is Agent related, a fix will come in a new agent version.

**Comment by Rantzur1992** [comment] 2021-04-18 08:03
@basdijkstra  I checked running an Android Test without start activity and it seems to work fine.
Can you show me the capabilities that you passed?

**Comment by Rantzur1992** [comment] 2021-04-18 08:22
@basdijkstra I see an issue where the test does not wait but fails right after with an ElementNotFound exception after the reset.

If I add some pause, or implicit waits, it does work (the app opens)


```
@pytest.fixture
def driver():

    app_activity = "io.testproject.demo.MainActivity"
    app_package = "io.testproject.demo"
    emulator_id = "emulator-5554"

    if not all([app_activity, app_package, emulator_id]):
        raise KeyError("Not all environment variables were set correctly.")

    desired_capabilities = {
        "appActivity": app_activity,
        "appPackage": app_package,
        "udid": emulator_id,
        "browserName": "",
        "platformName": "Android",
        "unicodeKeyboard": "true",
        "resetKeyboard": "true",
    }

    driver = webdriver.Remote(desired_capabilities=desired_capabilities)
    driver.reset()
    time.sleep(3)
    #  driver.start_activity(app_package=app_package, app_activity=app_activity)

    yield driver

    driver.close_app()
    driver.quit()
```

**Comment by basdijkstra** [comment] 2021-04-18 11:31
Does this mean that with proper waiting in place, the test would pass? Or is there something on the SDK side that needs fixing?

**Comment by Rantzur1992** [comment] 2021-04-18 12:02
Correct.
I don't think it's on the SDK side, just need to add some implicit wait to not fail the test immediately if an element is not found, since the app does open up.
The difference here, is that start activity waits until the app is open before moving to the next command, reset app moves forward before the app finishes opening, it it fails on finding the element since the app did not load yet.

**Comment by Rantzur1992** [comment] 2021-04-19 07:33
@basdijkstra Did you give it a try?

**Comment by basdijkstra** [comment] 2021-04-19 08:30
No, I haven't had the time for that yet. Can't do that before Wednesday.

**Comment by basdijkstra** [comment] 2021-04-21 15:11
I've played around with this a little, but even after adding a 20 second wait nothing happens after the `ResetApp()` call. Only when I add the call to `StartActivity()` the app reopens and my test continues as expected.

But if you say it works on your machine with the C# SDK, it should be something on my end. I've used the latest SDK code and the latest Agent (2.1.1).

If you can't reproduce it and it's no longer a problem, I think it is safe to close this issue. Agree, @Rantzur1992?

**Comment by Rantzur1992** [comment] 2021-04-26 15:54
I'll give it a few extra tries to see if I can reproduce it on different devices.

**Comment by Rantzur1992** [comment] 2021-05-02 05:29
I am not able to reproduce this, hence I am closing this ticket.
In case it comes up in a reproducible scenario, I will re open.

**Closed by Rantzur1992** 2021-05-02 05:29 UTC
Labels: bug, question
