### ISSUE TITLE
Incorrect page source content response

### ISSUE THREAD

**Issue by AnnaSwietek** [testproject-io/csharp-opensdk#168] opened 2021-04-13 12:41 UTC
After 
`driver.PageSource;`

we get a string response with the type on one of the tabs of our app on iOS
`System.Collections.Generic.Dictionary`2[System.String,System.Object]`

instead of full XML structure - in the attachment

It looks as if there is something unexpected in the XML structure, as for other tabs of the same app it works correctly.
Appium response is correct (the attachment)

To sum up, it is an iOS app with a tab view, and one tab is creating the above problem.

**Comment by basdijkstra** [comment] 2021-04-13 18:17
Is there a specific page URL that we can use to reproduce this issue, @AnnaSwietek? Especially because you say that it works for other pages when you're using the OpenSDK (or did I misinterpret that and does it fail for all pages)?

We simply extend the Selenium `RemoteWebDriver` that executes the `GetPageSource` WebDriver command as mentioned here:

https://github.com/SeleniumHQ/selenium/blob/e674eefec99cb04623e6c3f30605b4b63b07a934/dotnet/src/webdriver/Remote/RemoteWebDriver.cs#L230

**Comment by AnnaSwietek** [comment] 2021-04-14 07:55
To specify precisely, the problem occured on iOS native application, not on a web.

**Comment by basdijkstra** [comment] 2021-04-15 04:00
@Rantzur1992 can you take this up with @AnnaSwietek? See my latest email.

**Comment by Rantzur1992** [comment] 2021-04-20 11:13
Hi @AnnaSwietek 
Sent you an email about the IOS application.
I will close this issue, since we are continuing this over email.

**Closed by Rantzur1992** 2021-04-20 11:13 UTC
Labels: bug
