### ISSUE TITLE
Tests are not executing on Test Project (urgent)

### ISSUE THREAD

**Issue by Chrys123** [testproject-io/csharp-opensdk#253] opened 2021-11-18 11:55 UTC
There is an issue where the tests keep been skipped.

This was working before. You have changed something on the website and it doesnt work.

Coded Tests were running perfectly before.

Please fix immediately
[logs (6).zip](https://github.com/testproject-io/csharp-opensdk/files/7562512/logs.6.zip)

**Comment by s-glatshtein** [comment] 2021-11-18 12:04
Hi Chrys.
Can you please download the full logs of today and send them to support@testproject.io?
This must include the worker and browser logs of today

**Comment by Chrys123** [comment] 2021-11-18 12:13
Please resolve this immediately I have sent the logs

**Comment by vitalybu** [comment] 2021-11-18 13:02
@Chrys123, please keep the conversation civilized.
If you believe the issue is with the OpenSDK, you can always rollback to an older version.
Demanding an "immediate fix" doesn't help, and will NOT prioritize this issue over other issues. 
If you want to help resolving the issue as fast as possible, simply collaborate with the developers.

**Comment by Chrys123** [comment] 2021-11-18 13:06
I am not sure what the issue is please. It looks like it is with the website. I rolled back to a previous one and its not working.

Sorry, but simply this prevents me doing my job properly and i have had other issues which have not been looked at for a very very long time, 

This one is absolutely urgent and in my view it needs to be looked at immediately.

**Comment by s-glatshtein** [comment] 2021-11-18 14:06
Did you update anything? agent? SDK?

**Comment by Chrys123** [comment] 2021-11-18 14:16
Agent it says the minimum required is 1.2.4 so i tried with previous agents
and sdks to upload coded tests.

The tests work perfectly when I run them on the  dev environment on any
case but not when i upload them on the test project cloud.

I cannot complete the build integration task without this being resolved,
so i would appreciate if we can find out what is causing this so i can run
my tests smoothly from the cloud.

**Comment by mstrelex** [comment] 2021-11-18 18:33
@Chrys123 We are working on this and will keep you posted.

**Comment by mstrelex** [comment] 2021-11-18 19:02
@Chrys123 Please read my reply in mail.

**Comment by Chrys123** [comment] 2021-11-18 19:05
I replied there already

**Comment by Chrys123** [comment] 2021-11-19 08:32
OK so I downgraded to 95 Chrome as advised and I got the same thing

**Comment by s-glatshtein** [comment] 2021-11-25 10:01
Hi @Chrys123.
After a session where we re-uploaded the test package and deleted all cached coded tests, the problem was resolved.
Thanks for your cooperation on this matter!

**Closed by s-glatshtein** 2021-11-25 10:01 UTC

**Comment by Chrys123** [comment] 2021-11-25 10:05
Your welcome!!
