### ISSUE TITLE
Starting a new appium session right after a pervious one ends causes error

### ISSUE THREAD

**Issue by AnnaSwietek** [testproject-io/csharp-opensdk#154] opened 2021-03-24 09:39 UTC
Starting a new appium session right after a pervious one ends causes this error:

`Agent responsed with status code 499: [Operation interrupted]`

After the error the agent crashes and needs a manual restart to get back up

**Comment by basdijkstra** [comment] 2021-03-24 18:00
@AnnaSwietek can this be reproduced on your end simply by running two Appium tests in a row? If not, could you add a sample test I could use to try and reproduce it? 

@mstrelex what would make the Agent return an HTTP 499? Could it have something to do with timing?

**Comment by AnnaSwietek** [comment] 2021-03-25 11:22
@basdijkstra Please find logs attached
[logs.zip](https://github.com/testproject-io/csharp-opensdk/files/6204241/logs.zip)

**Comment by mstrelex** [comment] 2021-03-30 00:08
@basdijkstra 

On `2021-03-25 10:56:21.579`,  I see `Development socket disconnected` 
This happens during driver initialization interrupting development session initialization.

Earlier (`2021-03-25 10:56:19.677`) I see `Reusing existing development session.
Can you please check whether the TCP socket connection is kept open between consequent tests?

**Comment by basdijkstra** [comment] 2021-03-30 15:16
@mstrelex it is, whenever I run and report multiple tests that are supposed to be in the same job, they are indeed reported in the same job. That couldn't happen if the socket connection was closed in between tests..

**Comment by mstrelex** [comment] 2021-03-30 23:57
@basdijkstra That's right.
@AnnaSwietek could you please share more details regarding your scenario?

**Comment by AnnaSwietek** [comment] 2021-04-06 09:08
Hi Ran Tzur,

Could you let us know which openSDk will have the fix in place?

Thank you & BR,
Anna

**Comment by Rantzur1992** [comment] 2021-04-06 09:11
All SDKs will have it, since the implementation will be on the Agent side.

**Comment by Rantzur1992** [comment] 2021-04-08 09:05
Hi @AnnaSwietek I tried the following:

Had 3 tests on Android, with one setup where the driver is started, and a quit at the end, and each appium session started and stopped as expected.

Do you have some example code?

**Comment by AnnaSwietek** [comment] 2021-04-13 12:24
I believe the problem is more high level and it is related to the fact that TestProject does not manage to generate the report fast enough.

**Comment by Rantzur1992** [comment] 2021-04-20 12:41
I am closing this, as we are continuing over email.

**Closed by Rantzur1992** 2021-04-20 12:41 UTC
Labels: bug
